### ISSUE TITLE
Support for different Study Types

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#90] opened 2019-08-19 05:36 UTC
We need support for different types of studies, e.g. "Simplified Screening", "Screening", "Expert" and probably some more (baseline vs. adaptation study). ATM the study types just differ in the number of steps shown. Later we may need custom configuration on per-steps basis, e.g. to show / hide additional external applications (via iFrame) like the Envi-Met (?) 3D Viewer used by DC3.

So https://github.com/clarity-h2020/docker-drupal/issues/83 should be extended accordingly.

- for  "Simplified Screening" studies we would need just HC and EE and perhaps IA/RA.
- for Expert Studies, we daon't need HC-LE
- tbc

**Comment by DenoBeno** [comment] 2019-08-19 06:30
What happens if gl_step node is missing for some step? Does the related step disappear from the GUI? Can one still see & visit other steps?

If so, we could change the Business rules so that gl steps are generated "just in time". 

This would also make it easier to produce conditional business rules for different study types.

**Comment by DenoBeno** [comment] 2019-08-19 12:36
I worked on this with Florian today, and we have a (IMO) great concept.

1) gl step node can be declared as "template" (done)
2) gl step nodes of template type can be referenced from the study type (almost done)
3) change the business rules so that they generate the gl steps corresponding to the templates listed in study type. (todo)

This will make the process of adding new study types extremely flexible and easy. Best of all:
- Initial set of templates can be made by adding a new study and then editing the gl step nodes to declare them as templates.
- later, we can easily clone the existing ones and change what needed.
- necessary business rules are study type independent.
- while we are at it, the business rule can first delete any existing gl steps belonging to the group (if any) and then add new ones.

**Comment by DenoBeno** [comment] 2019-08-19 12:42
By the way, we also tested what happens if some steps aren't generated. Steps that aren't generated aren't showing up. 

The problem could be that we are currently preventing people from skipping steps - what happens if some step doesn't exist?

**Comment by DenoBeno** [comment] 2019-08-19 12:55
btw, i wonder how to best support additional application types. E.g. the 3D viewer.

Would the 3D viewer appear on its own sub-step, or would it appear e.g. on existing map or table sub-step?

Can more than one application appear on the same sub-step?

**Comment by p-a-s-c-a-l** [comment] 2019-08-19 13:12
> Would the 3D viewer appear on its own sub-step, or would it appear e.g. on existing map or table sub-step?

I would put it on a separate sub-step. 

> Can more than one application appear on the same sub-step?

If we embed it as iFrame, then it's no problem. With ReactMount it's not possible AFAIK.

I asked @toetzert for the URL of the DC3 3D Viewer presented in Vienna  (AFAIR it visualises the output of envi-met local model for Linz). Then we can asses whether and how this external 3D viewer could be embedded as iFrame.

**Comment by DenoBeno** [comment] 2019-08-19 15:56
I have implemented the possibiltiy to define which steps go to which studies and also to change the step template per study. It's really easy to use.

1. start from taxonomy overview https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/study_type/overview
2. Add new study type (or edit existign one) - btw, I have no idea what is "study type id" field for

![grafik](https://user-images.githubusercontent.com/2961790/63278501-a54b1900-c2a7-11e9-8ecc-91748d1cc297.png)

3. Add some existing templates. there is a filtering possibility to find the right ones.

![grafik](https://user-images.githubusercontent.com/2961790/63278591-d62b4e00-c2a7-11e9-9066-1b6dc1f4ee48.png)

4. If necessary, duplicate to produce new templates for this study type.

![grafik](https://user-images.githubusercontent.com/2961790/63278649-f6f3a380-c2a7-11e9-8932-00bc0fb11d29.png)

![grafik](https://user-images.githubusercontent.com/2961790/63278736-20acca80-c2a8-11e9-8219-2a31dab68d81.png)

5. Save!!!!

Without saving, there will be problems, so save first now.

5. If you have duplicated the study step, delete the other one from this list. Do not delete it from the system. 

![grafik](https://user-images.githubusercontent.com/2961790/63278981-8a2cd900-c2a8-11e9-86f0-1aa1460234a5.png)

![grafik](https://user-images.githubusercontent.com/2961790/63279014-99138b80-c2a8-11e9-9a0e-e51fecd03b5e.png)

SHIT!!!! DUPLICATED ENTRIES CAN'T BE STORED - YET ANOTHER BUG REPORT FOR THE MODULE.

https://www.drupal.org/project/inline_entity_form/issues/3075872

OK, I'll rewrite this so that it can be used...

**Comment by DenoBeno** [comment] 2019-08-19 16:05
OK, I have rewritten this so that no duplication is possible. Also no adding of new steps per hand.

In order to add new templates, do the following: 

1) add a new study (call it "template study X" or such) of a type you wish to start with.
2) go to https://csis.myclimateservice.eu/admin/content and edit the new eu-gl steps. Those that have just been generated will be on top (8 of them for a standard study as we have today).
3) Edit these entries "as Template". At least change the "template name"

![grafik](https://user-images.githubusercontent.com/2961790/63280839-d1689900-c2ab-11e9-92e1-8c5154463bd3.png)

4) Save. New templates wil lbe availableto be linked with study type taxonomy.

If and w3hen duplication becomes possible, we wil lnot need to work in this way. In the meantime, it's good enough for us.

**Comment by DenoBeno** [comment] 2019-08-19 16:31
I have tested this and it works, but it's a bit of a PITA.

![grafik](https://user-images.githubusercontent.com/2961790/63282225-9d42a780-c2ae-11e9-89c3-7c550a5a389e.png)

![grafik](https://user-images.githubusercontent.com/2961790/63282292-cebb7300-c2ae-11e9-930a-ff603bbf11fd.png)

Therefor I've also added the possibility to add new template in the entity browser.

![grafik](https://user-images.githubusercontent.com/2961790/63282534-4e494200-c2af-11e9-8daa-66b1b2e2dba5.png)

![grafik](https://user-images.githubusercontent.com/2961790/63282605-7b95f000-c2af-11e9-8a2f-26cc22f017af.png)

I do hope that this will work, but I'm not going to test it because there are too many fields that need to be set.... I hope nobody will ever use this.

**Comment by DenoBeno** [comment] 2019-08-19 16:46
@fgeyer16 : adding new studies is broken at the moment, the eu-gl steps don't get added to the study group. I'm not touching this, it has to be rewritten anyway. Can you do the new rules?

This is what you can test with:

https://csis.myclimateservice.eu/taxonomy/study-type/simple-study
https://csis.myclimateservice.eu/taxonomy/study-type/urban-infrastructure

They have been defined to use different templates (well, templates have different IDs and names, they are the same otherwise for now.) and differnt number of templates.

**Comment by DenoBeno** [comment] 2019-08-20 14:41
For the record: beta7 of busines rules is broken, so I wasn't able to get the new rules working. I'm pretty far though. it should be straightforward if beta 8 works as it should...

In addition to #95, there is another bug that can be worked around if necessary: apparently setting boolean fields doesn't work. If this is true, we'll have to replace "is_template" by a numeric or string field. :-(

In order to work around another bug mentioned above embedded, I have removed the "template name" and replaced it with "step label". The busines rule should overwrite the title field with value of this field when producing eu-gl steps. In this way, we can rename the templates in anything we see fit.

**Comment by DenoBeno** [comment] 2019-08-20 14:47
https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields/node.gl_step.field_template_name

For info: I haven't removed the field, I just gave it a new label & description

![image](https://user-images.githubusercontent.com/2961790/63357670-15ba6e80-c36a-11e9-9b11-9bc88adc0c33.png)

**Comment by patrickkaleta** [comment] 2019-08-21 07:34
> @fgeyer16 : adding new studies is broken at the moment, the eu-gl steps don't get added to the study group. I'm not touching this, it has to be rewritten anyway. Can you do the new rules?
> 

Comparing the current setup of this business rule on the live CSIS and my local instance, I noticed that the workflow of this business rule seems to have been (by accident?) changed: (left side my local instance, right side CSIS):
![br-new-study-bug](https://user-images.githubusercontent.com/42167036/63411628-3cbe8200-c3f6-11e9-96c0-9f4e9bd8ee85.png)

The "Show last 8 GL-steps..." is needed for adding the newly created GL-Steps to the Study group. Taking this step out of the workflow would fit the faulty behaviour mentioned above by @DenoBeno.

**Comment by patrickkaleta** [comment] 2019-08-21 10:17
> For the record: beta7 of busines rules is broken, so I wasn't able to get the new rules working. I'm pretty far though. it should be straightforward if beta 8 works as it should...

I updated business rules to beta8. Tests in my local environment however didn't seem to be very promising.

**Comment by DenoBeno** [comment] 2019-08-22 17:31
Implementation is almost finished. The rules for UPDATING the study are already updated, you can start testing NOW.

Please test:

1. Add new study
2. Change study type
3. See if the GL steps are defined as they should be.

Once this is OK, I just need to change the rule for adding new study. I hav ealready described what to do here: https://csis.myclimateservice.eu/admin/config/workflow/business_rules/creat_study_content_/edit?destination=/admin/config/workflow/business_rules/collection

It's *very* simple to do. This rule just needs to call two loops that are already used in "update" rule, all the actions that it currently lists can (must)  be removed.

**Comment by DenoBeno** [comment] 2019-08-22 18:57
OK, I have simplified this. 

Old "insert" rule: https://csis.myclimateservice.eu/admin/config/workflow/business_rules/creat_study_content_/edit

New insert rule: https://csis.myclimateservice.eu/admin/config/workflow/business_rules/create_study_contents/edit

![image](https://user-images.githubusercontent.com/2961790/63587481-6c12f180-c5a4-11e9-9059-ba470397f35a.png)


Old one just needs to be disabled (we can delete it later) and the new one enabled. But first test with the "update" rule please.

**Comment by DenoBeno** [comment] 2019-08-23 10:47
I have enabled the new "insert" rule. To the best of my knowledge this works as designed now, so I'm closing the issue. 

If any issues are encountered, please first double-check the template definitions. If a template defines a wrong application or view, then the study will be broken. 

@p-a-s-c-a-l: only one template has MCDA date defined in it, this one https://csis.myclimateservice.eu/node/938/edit/template. I understand that this isn't used in any other step...

**Closed as completed by DenoBeno** 2019-08-23 10:47 UTC
Labels: enhancement, BB: Scenario Management
