### ISSUE TITLE
Jorge Amorim can not login to the system

### ISSUE THREAD

**Issue by LenaStr** [clarity-h2020/docker-drupal#103] opened 2019-08-27 14:20 UTC
Jorge can not login to CSIS. It seems to be the same problem that Anna had before, thet the e-mail has been used in a previous version of the account.

It did not hel that I changed the password.

Username: jorge.amorim
E-mail: jorge.amorim@smhi.se

**Comment by p-a-s-c-a-l** [comment] 2019-08-29 05:28
@fgeyer16 Did you look into this?

**Comment by fgeyer16** [comment] 2019-08-29 17:03
Yes I am on it.

**Comment by fgeyer16** [comment] 2019-09-02 12:41
Jorge can log in now closing

**Comment by p-a-s-c-a-l** [comment] 2019-09-04 08:19
Not working again, either via https://csis.myclimateservice.eu/ OR https://profile.myclimateservices.eu/
Jorge is always redirected to https://csis.myclimateservice.eu/user/login and cannot log in.

System Log message:

![grafik](https://user-images.githubusercontent.com/1788226/64237736-3dc6d780-cefd-11e9-9c5d-6606a0ce8afa.png)

Those failed login attempts are probably related to https://github.com/clarity-h2020/docker-drupal/issues/105 as the system uncontrollably started to send mails today.

**Comment by fgeyer16** [comment] 2019-09-04 13:46
The cause seems to be the restoring of csis from backup Monday afternoon. With that soe cahnegs in Jorges profile I did were undone as well.
Waiting for Jorge ś confirmation that he can login again

**Comment by fgeyer16** [comment] 2019-09-04 14:05
Jorge can login again so closing again.

**Closed as completed by fgeyer16** 2019-09-04 14:05 UTC
Labels: bug, BB: Infrastructure
