### ISSUE TITLE
Navigation tabs disappear

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#80] opened 2019-07-08 11:47 UTC
Navigation tabs disappear when switching in Study from any tab to "Summary":

![bugbugbug](https://user-images.githubusercontent.com/1788226/60807743-c7b92500-a186-11e9-8f1b-9098ad69aab6.gif)

**Comment by patrickkaleta** [comment] 2019-07-24 09:26
@fgeyer16 what I was able to find out so far:
- this bug appears only after the first load of the summary tab after the cache has been cleared
- using the Webprofiler tool in the Devel module I learned that the following views are not loaded:
  - `study_group_main_navigation_v2`
  - `study_group_tabs_for_group`
  - but instead additionally the `dp_license_eva` view is loaded
- also only 10 instead of 11 blocks are rendered:
  - not rendering `views_block__study_group_main_navigation_v2_block_2`
  - not rendering `views_block__study_group_tabs_for_group_block_1`
  - but instead the `csis_page_title` block is rendered

It seems the the view [EVA Group maps](https://csis.myclimateservice.eu/admin/structure/views/view/report_summary_images/edit/group_maps) is causing this bug. When I remove this view from the [Summary display](https://csis.myclimateservice.eu/admin/group/types/manage/study/display/summary) of the Study group, the bug does not appear. Also, creating a separate display mode and showing only this view leads to the same buggy behaviour.

But I still haven't figured out why exactly this view is causing this bug.

**Comment by patrickkaleta** [comment] 2019-07-24 10:45
### Update:
Changing the `Show` option from "Content" to "Fields" of the previously mentioned view helped solve the bug. Instead of showing the Report images in the default display mode (the case for using `Show` option = "Content"), I recreated the default display mode directly inside the view.

@fgeyer16 could you think of a reason, why this was the cause for this bug? I wasn't able to find any related EVA issues for this kind of bug online.

**Comment by fgeyer16** [comment] 2019-07-24 15:58
> @fgeyer16 could you think of a reason, why this was the cause for this bug? 

Not really for now. What lead you to try the show option Fields instead of Content?

**Comment by patrickkaleta** [comment] 2019-07-25 07:38
> > @fgeyer16 could you think of a reason, why this was the cause for this bug?
> 
> Not really for now. What lead you to try the show option Fields instead of Content?

Mostly pure desperation ;-) 
But also I was wondering if the set "summary" display inside this view might have somehow interfered with the overall "summary" display of the whole Study group page. However, changing to another display form still led to the same bug. Switching to show "Fields" instead finally did the trick then.

**Comment by DenoBeno** [comment] 2019-09-11 15:41
Seems to work now. Close?

**Comment by patrickkaleta** [comment] 2019-09-12 08:59
The tabs haven't disappeared since, so I'm closing this now.

**Closed as completed by patrickkaleta** 2019-09-12 08:59 UTC
Labels: bug, BB: UI Integration Platform
